language: python
sudo: true
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsasl2-dev libssl-dev libdb-dev
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout coveralls
install:
  - ./bin/buildout
script:
  - ./bin/test
after_success:
  - bin/createcoverage
  - bin/python -m coverage.pickle2json
  - bin/coveralls
